general =
{
  name = "Pi AirPlay";
  volume_range_db = 60;
};

audio_backend = "alsa";

alsa =
{
  output_device = "hw:sndrpihifiberry";
  mixer_control_name = "";
};

metadata =
{
  enabled = "yes";
  include_cover_art = "no";
  pipe_name = "/tmp/shairport-sync-metadata";
};
